---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default

commonLabels:
  app.kubernetes.io/name: arborist
  app.kubernetes.io/version: 1.0.0

resources:
- deployment.yaml
- service.yaml
- ingress.yaml
